version: "3.9"


services:

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ../data:/data
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: djangoapp-db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin

  panel:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 80:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_HOST: db
    depends_on:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db

  # geckodriver:
  #   image: blueimp/geckodriver
  #   # Mount the /tmp partition as tmpfs:
  #   tmpfs: /tmp
  #   # Set the size of the /dev/shm partition:
  #   shm_size: 2g
  #   environment:
  #     # Enable the VNC server:
  #     - ENABLE_VNC=true
  #     # Expose the X Window Server via TCP:
  #     - EXPOSE_X11=true
  #   volumes:
  #     # Mount the host ./assets directory into the container:
  #     - ./scrapers/:/home/webdriver/assets
  #   ports:
  #     # Expose the VNC server on port 5901 on localhost:
  #     - 127.0.0.1:5901:5900