version: "3.9"


services:

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: djangoapp-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  panel:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 80:80
    environment:
      PMA_USER: admin
      PMA_PASSWORD: admin
      PMA_HOST: db
    depends_on:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db