# Generated by Django 4.0.1 on 2022-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0002_productoffer_image_productoffer_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='shop',
            field=models.CharField(max_length=20),
        ),
    ]
